[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastexcel>=0.14.0",
    "pandas>=2.3.2",
    "pillow>=11.3.0",
    "polars>=1.32.3",
    "tqdm>=4.67.1",
    "xlsxwriter>=3.2.5",
]
